### ISSUE TITLE
Distributing Work

### ISSUE THREAD

**Issue by notmemoto** [joesocktwo/Wall-Street-Bets-Master-Doc#4]
Hello All,

I think we should have some sort of sign up sheet(or something similar) to distribute work. Doing so will help set clear goals, avoid redundancies, promote organization, and assign some sort of accountability. We're all here to make some tendies, so let's do it properly. Let me know what you guys think, because this will only work if we are on the same page.

**Comment by joesocktwo** [comment]
Agreed. I'm taking a largely hands-off approach with this. I've been accepting collaborators all day, though.

The main subject to be investigated is at-risk foreign banks. By and large, the most vulnerable will be in emerging markets. Some European banks are at risk and will take a beating, but likely won't go under, except perhaps in Italy or Greece. India, in particularly, has a very fragile banking system; if banks start going under, they might end up going the way of Yes Bank and get nationalized.

A few avenues to pursue would be checking Basel 3 reports (individual banks aren't disclosed, but regional stats can give a good sense of which parts of the world have the weakest banks, per CET1-RWA ratios) and checking CDS spreads (follow the smart money). Most of the world is still only complying with GAAP and IFRS standards, which means their holdings won't always be disclosed, which makes this difficult. Additionally, there will be lots of vulnerable banks that aren't publicly traded, but to which publicly traded companies and banks are exposed (EG Barclay's and ABSA).

A good way to begin would be enumerating banks for analysis and then passing them off to a group of FA wonks for detailed study. Once the FA people have concluded a bank isn't safe, a TA group could put together indicators and setting up alerts for those banks. Need an eye on the news at all times, too, since quarantines and supply disruptions are going to likely be the impetus for defaults in a given area.

I'm happy to help, if someone wants to point me in the right direction. I'm honestly not that useful. I just wrote some words that people liked on the internet.

For comments, questions and concerns, hit me up on reddit.

Cheers,
u/joesocktwo

**Comment by notmemoto** [comment]
I actually think US banks will take a beating too. Definitely not as much as forgiven banks though. (More on that soon) As for the work distribution. I can work on a system and I encourage others to do so as well. We can adopt one most people agree on.

**Comment by Lacheankey** [comment]
I can start looking into reports and finding the weak points. I'm here to learn so if there is any grunt work that needs to be done, let me know.

**Comment by tendiequest** [comment]
I’d suggest a simple Trello board, this way we can let people pick up tasks as well as see progress on them. 

Demo: https://trello.com/b/2rdyTVWx/training-board

**Comment by GokuDoku** [comment]
Let me know how I could best help. Happy to put in some focused research hours if there’s a specific vein to follow

**Comment by joesocktwo** [comment]
Join the discord, y'all

**Comment by GokuDoku** [comment]
What’s the link @joesocktwo
